[package]
name = "dot_vox"
version = "0.4.0"
authors = ["David Edmonds <edmonds.d.r@gmail.com>"]
description = "A Rust library for loading MagicaVoxel .vox files."
license = "MIT"
keywords = ['voxel', 'MagicaVoxel', 'game', 'game-dev']
documentation = "https://docs.rs/dot_vox"
homepage = "https://docs.rs/dot_vox"
repository = "https://github.com/davidedmonds/dot_vox"
readme = "README.md"

[dependencies]
nom = "^3.0"
byteorder = "^0.5.3"

[dev-dependencies]
avow = "0.2.0"